const goats = [
  {
    id: 'goat1',
    name: 'billy',
    disposition: 'rude',
    imageurl: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Hausziege_02.jpg',
    fullness: 67,
    favPose: 'downward facing dog',
    isfainting: true,
    color: 'brown',
  },
  {
    id: 'goat2',
    name: 'tom',
    disposition: 'rude',
    imageurl: 'https://media.mnn.com/assets/images/2016/07/goats-wattles.jpg.838x0_q80.jpg',
    fullness: 79,
    favPose: 'downward facing dog',
    isfainting: true,
    color: 'white',
  },
  {
    id: 'goat3',
    name: 'Nanny',
    disposition: 'rude',
    imageurl: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Hausziege_02.jpg',
    fullness: 88,
    favPose: 'downward facing dog',
    isfainting: true,
    color: 'white',
  },
  {
    id: 'goat4',
    name: 'Pan',
    disposition: 'rude',
    imageurl: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Hausziege_02.jpg',
    fullness: 80,
    favPose: 'downward facing dog',
    isfainting: true,
    color: 'brown',
  },
  {
    id: 'goat5',
    name: 'Murphy',
    disposition: 'rude',
    imageurl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCRdYbwd5au0aYMxMT0odDyuN-dAzuATeiUMATLq4nnTwQPKsQ',
    fullness: 90,
    favPose: 'downward facing dog',
    isfainting: true,
    color: 'black',
  },
];
export default { goats };
